- d/kitstrap.css
- docs/custom.css
- docs/elements.html
- docs/index.html
- docs/installation.html
- docs/layouts.html
Hierarchize Sample Document
close #1
> Hierarchize Sample Document [0.2]

- d/kitstrap.css
- docs/elements.html
- docs/index.html
- docs/installation.html
- docs/layouts.html
Add .large and .small
close #5
> Add Child Class "small" and "large" to kit-button [0.2]

- d/kitstrap.css
- docs/elements.html
- docs/layouts.html
> Add Button Group [0.2]

- d/kitstrap.css
Add Font Size Properties
close #2
> Add Font Props and Bug Fix [0.2]

- d/kitstrap.css
Add Support for `.kit-space`, `.kit-container`
> Adding support for .kit-space .kit-container

- d/kitstrap.css
Format Selectors at d/kitstrap.css
close #14
> Format CSS Selectors [0.2]

- d/kitstrap.css
- docs/elements.html
- docs/fonts.html
- docs/index.html
- Add ".dark" Class for Some Elements
- Such as `.textbox.dark`
- Add "kit-pane" Element
- It Has Subclasses `.dark` and `.hover`
- Add Documentation for Fonts or Text
close #15
> Add ".dark" Subclass

- d/kitstrap.css
> fixes kit-box:only-child

- d/kitstrap.css
- docs/elements.html
Add ".disabled" Child Class to kit-button and textbox
close #20
> Add ".disabled" Child Class to kit-button and textbox [0.2]

- d/kitstrap.css
- docs/elements.html
- docs/fonts.html
Add ".xlarge" Subclass for kit-button and a X-Large Prop for kit-font
close #24
> Add X-Large Size Props for Font and Button

- d/kitstrap-cursor.css
- d/kitstrap.css
- docs/elements.html
- Toggle System is Available by Using "kit-toggle" and `label` Elements
close #26
> Add Kitstrap Toggle System [0.2]

- d/kitstrap.css
- Increase Specificity of Some General Classes by Repeating Same Selectors
close #29
> Increase Specificity of Some General Classes [0.2]

- d/kitstrap.css
- docs/elements.html
- Add ".kit-formgroup" to Group Some Form Elements
close #22
> Add ".kit-formgroup" Instead of Legacy ".kit-buttongroup"

- d/kitstrap.css
- docs/elements.html
- "kit-formgroup" Includes Effect to "kit-btn"
close #33
> Add kit-formgroup Function for kit-btn Elements

- d/kitstrap.css
- docs/custom.css
- docs/elements.html
- docs/fonts.html
- docs/layouts.html
- Improve Font Rendering at Some Environment
- close #39 
- Update Default Fonts
- close #38 
- Scrollbar Design is Updated
- `pre` and `code` Elements Design is also Updated
- Add `.kit-scroll` Class for Scrollable Contents
- BEFORE
- AFTER
> Improve Font Rendering and Update Default Fonts [0.3]

- d/0.2/kitstrap-cursor.css
- d/0.2/kitstrap-font.css
- d/0.2/kitstrap.css
- Bundle Legacy Versions in `d` Directory
close #43
> Bundle Successive Versions of kitstrap [0.3]

- d/kitstrap.css
- Update Mono-space Fonts for `pre` Elements
> Update Font Style of `pre` [0.3]

- d/kitstrap.css
- docs/installation.html
- Add kitstrap Flex System
- kit-inline-flex
- kit-flex-row
- kit-flex-row-reverse
- kit-flex-column
- kit-flex-column-reverse
- kit-flex-nowrap
- kit-flex-grow
- kit-flex-shrink
- kit-flex-start
- kit-flex-end
- kit-flex-center
- kit-flex-fit
- kit-flex-top
- kit-flex-middle
- kit-flex-bottom
close #8
> #8 Add kitstrap Flex System

- d/kitstrap.css
- docs/elements.html
#Outline
- Add Prefix to All Child Color Classes
- For Instance: `.-green`, `.-deeppink` or `.-dodgerblue`
close #49
> #49 Add Prefix to Color Class

- d/kitstrap.css
- docs/layouts.html
- ex) **top** : `.m-t-0`, `.m-t-s`, `.m-t`,`.m-t-m`, `.m-t-l`, `.m-t-xl`
close #52
> #52 Add Direction Option to Padding and Margin Classes

- d/kitstrap-font.css
- d/kitstrap.css
- docs/layouts.html
- `.p-left` : Add Padding to Left of the Element.
- `.m-left` : Add Margin to Left of the Element.
> #0 Resolve Conflicts of Classes Name

- d/kitstrap.css
- docs/elements.html
- docs/fonts.html
- docs/layouts.html
- Add Documentation about Flex System
> #0 Add Documentation About kitstrap Flex System

- d/kitstrap.css
- docs/custom.css
- docs/fonts.html
- Add Styles for Heading Elements(`h1` to `h5`)
close #40
> #40 Add Styles for Heading Elements

- d/kitstrap.css
- docs/elements.html
- Define Width of Elements by Properties
- `.kit-width-25` `.kit-width-50` `.kit-width-75` `.kit-width-100`
- Define Max Width of Elements by Properties by `.kit-fit`
- Add Some Width Props as Child Class of `.textbox`
> #41 Add Width Properties

- d/kitstrap.css
- Remove the Definition of "#kit-wallpaper"
close #63
> #63 Remove #kit-wallpaper

- d/kitstrap.css
- docs/custom.css
- docs/elements.html
- Add `.kit-notice` Class.
- It Has Some Color Variation as Child Classes (`.-green`, `.-yellow`, `.-red` and `.-black`).
close #51
> #51 Add a Class for Notices

- d/kitstrap.css
- Set the box-sizing prop of ".textbox" to "border-box"
close #66
> #66 Set the box-sizing prop of ".textbox" to "border-box"

- docs/index.html
- docs/util.html
- Add Documentation of Utilities Classes
> #0 Add Documentation of Utilities Classes

- d/kitstrap.css
- docs/elements.html
- Add child class `.-flat` that make `kit-button` simple design.
close #70
> #70 Add flat kit-button

- d/kitstrap.css
- docs/fonts.html
- docs/util.html
- `.kit-font-0` will set font-size to zero.
- `.kit-line-0` will set line-height to zero.
close #72
> #72 Add classes to set font-size or line-height to "0"

- d/kitstrap.css
- docs/fonts.html
- Add classes to change text color that has`.kit-clr`prefix.
- Add classes to change background color that has`.kit-bgclr`prefix.
close #74
> #74 Add color classes and background color classes

- d/kitstrap.css
- Add `.kit-flex-wrap` and `.kit-flex-wrap-reverse`
close #69
> #69 Add "wrap" classes to kit-flex system

- d/kitstrap-cursor.css
- d/kitstrap.css
- docs/elements.html
- Add `.kit-input-file` for `input[type=file]`
close #79
> #79 Add support for input[type="file"]

- d/kitstrap.css
- docs/elements.html
- Fix `.kit-button` for iOS
close #78
> #78 Fix kit-button for iOS

- d/kitstrap.css
- docs/elements.html
- Add tooltips to kitstrap by using elements `.kit-tipped` and `.kit-tip`.
close #86
> #86 Add ".kit-tipped" and ".kit-tip" for tooltips

- d/kitstrap.css
- docs/util.html
- Add width properties every 5%.
close #91
> #91 More detailed width properties

- d/kitstrap.css
- docs/elements.html
- Add `.kit-breadcrumb` class to set up the breadcrumb.
close #89
> Add breadcrumb

- d/kitstrap.css
- docs/util.html
- Add classes for shadows of some elevations
close #97
> #97 Add shadow elevation classes

- README.md
> #0 Update README.md [0.5]

- README.md
- package-lock.json
- package.json
- Init npm
```sh
npm i kitstrap
```
> #0 Initialize npm

- LICENSE
> #0 Create LICENSE

- README.md
- d/kitstrap.css
- docs/elements.html
- docs/fonts.html
- docs/form.html
- docs/index.html
- docs/installation.html
- docs/layouts.html
- docs/util.html
- Update documentation and README for v0.6 alpha
> #0 Update docs

- d/kitstrap.css
- docs/installation.html
- docs/layouts.html
- Add `x` and `y` suffix to margin and padding.
close #113
> #113 Add x and y suffix to padding and margin

- d/kitstrap.css
- docs/fonts.html
- Fix style of code tag in pre, blockquote tag
close #111
> #111 Fix style of code tag inside pre, and blockquote tag

- d/kitstrap.css
- docs/fonts.html
- Add kit-font-xxl for xxl size.
close #112
> #112 Add XX-Large and X-Small fonts

- d/kitstrap.css
- Add style for buttons that has a `disabled` attribute.
> #116 Style for buttons which has disabled attr

- .github/workflows/release.yml
Add a workflow to deploy documentation
> Add a workflow to deploy documentation

- d/kitstrap.css
- docs/docs/.vuepress/config.js
- docs/docs/elements.md
- docs/elements.html
- docs/fonts.html
- docs/form.html
- docs/index.html
- docs/installation.html
- docs/layouts.html
- docs/util.html
Add the style for table elems
close #130
> #130 Add table style

- README.md
- d/kitstrap.css
- docs/docs/.vuepress/config.js
- docs/docs/README.md
- docs/docs/guide.md
- docs/yarn.lock
- package-lock.json
- package.json
> Release kitstrap v0.7.1
